"""Real, live-generated example GoalRuns + a real HarnessSuggestion for the
Chief of Staff dashboard page, loaded exactly like
app/dashboard_ui/example_traces.py's success examples (no live Gemini key
on the public Streamlit Cloud deployment).

Generated by scripts/generate_cos_examples.py -- both GoalRun outcomes are
genuinely real, unscripted LLM behavior, not cherry-picked to look tidy:
one run genuinely failed all 3 attempts at a one-paragraph constraint
(GoalCompletionChecker correctly caught the violation every time), the
other genuinely achieved a broader goal in its first attempt despite a
tight max_iterations=1 budget. The HarnessSuggestion is grounded in the
real committed failure_traces.json + eval_history.json data, not invented
for this file.
"""

import json
from pathlib import Path

from app.proactive.goal_run import GoalRun
from app.proactive.harness_feedback import HarnessSuggestion

_COS_EXAMPLES_PATH = Path(__file__).resolve().parent / "cos_examples.json"


def load_example_goal_runs() -> list[GoalRun]:
    if not _COS_EXAMPLES_PATH.exists():
        return []
    raw = json.loads(_COS_EXAMPLES_PATH.read_text())
    return [GoalRun.model_validate(r) for r in raw.get("goal_runs", [])]


def load_example_harness_suggestion() -> HarnessSuggestion | None:
    if not _COS_EXAMPLES_PATH.exists():
        return None
    raw = json.loads(_COS_EXAMPLES_PATH.read_text())
    suggestion = raw.get("harness_suggestion")
    return HarnessSuggestion.model_validate(suggestion) if suggestion else None


def seed_cos_examples(goal_run_store, harness_suggestion_store) -> tuple[int, int]:
    """Idempotent: GoalRunStore.save()/HarnessSuggestionStore.save() are
    both INSERT OR REPLACE keyed by their own id, so re-seeding never
    duplicates."""
    goal_runs = load_example_goal_runs()
    for run in goal_runs:
        goal_run_store.save(run)

    suggestion = load_example_harness_suggestion()
    if suggestion is not None:
        harness_suggestion_store.save(suggestion)

    return len(goal_runs), (1 if suggestion is not None else 0)
