"""Real, live-generated failure-mode example traces for the Traces page,
loaded exactly like app/dashboard_ui/example_traces.py's success examples
(same reason: no live Gemini key on the public Streamlit Cloud deployment).

Generated by scripts/generate_failure_traces.py -- 3 real scenarios, not
fabricated:
  1. Tool failure (calculator division by zero) -- caught and recovered
     from, real bug fix in app/agents/tool_agent.py.
  2. Retrieval failure -- a real index with no relevant content, measured
     against a real human-labeled ground truth (0 relevant chunk ids),
     showing a real precision=0.0 span-level failure while the trace still
     completes.
  3. Budget-exhausted -- a tool that fails on every attempt, stopped by the
     real AgentBudget.max_tool_calls backstop (deterministic, no live API
     call -- see that script's docstring for why).

Regenerate after any change to app/agents/tool_agent.py's error handling or
app/observability/traces.py's schema.
"""

import json
from pathlib import Path

from app.observability.trace_store import TraceStore
from app.observability.traces import Trace

_FAILURE_TRACES_PATH = Path(__file__).resolve().parent / "failure_traces.json"


def load_failure_trace_records() -> list[dict]:
    """Raw records ({"input_text", "trace_json"}), for dashboard code that
    wants the input text alongside the parsed Trace without a second lookup."""
    if not _FAILURE_TRACES_PATH.exists():
        return []
    return json.loads(_FAILURE_TRACES_PATH.read_text())


def seed_failure_traces(trace_store: TraceStore) -> int:
    """Same idempotent seeding pattern as example_traces.seed_example_traces:
    TraceStore.save() is INSERT OR REPLACE keyed by execution_id, so
    re-seeding never duplicates."""
    records = load_failure_trace_records()
    for record in records:
        trace = Trace.model_validate(record["trace_json"])
        trace_store.save(trace, input_text=record["input_text"])
    return len(records)
